version: '3.2'
services:
  application:
    image: application:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  documentation:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./target/site/apidocs/:/usr/share/nginx/html